---
title: "Mandated reporting and family surveillance"
author: "Frank Edwards and others"
date: "10/30/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(tidyverse)
source("process_imputed_ncands.r")
source("read.r")
theme_set(theme_minimal())
```


# National overview

## Report source

```{r}
plot_dat<-nat_ncands %>% 
  filter(.imp==1) %>% 
  left_join(pop %>% 
              filter(year%in%nat_ncands$year,
                     age<=18) %>% 
              group_by(age) %>% 
              summarise(pop = sum(pop))) 

rpts_pc<-plot_dat %>% 
  group_by(.imp, year, age, rptsrc) %>% 
  summarise(n_total = sum(n_total),
            pop = sum(pop)) %>% 
  mutate(total_pc = n_total/pop) %>% 
  ungroup()


ggplot(rpts_pc,
       aes(x = age, y = total_pc * 1000)) + 
  geom_line() +
  #geom_ribbon(alpha = 0.5) +
  facet_wrap(~rptsrc) + 
  labs(title = "Child subjects of CPS investigations",
       subtitle = "US, 2018",
       y = "Rate per 1,000",
       x = "Age")

```


```{r}
plot_dat<-nat_ncands %>% 
  filter(.imp==1) %>% 
  left_join(pop %>% 
              filter(year%in%nat_ncands$year,
                     age<=18) %>% 
              group_by(age, race_ethn) %>% 
              summarise(pop = sum(pop))) 

rpts_pc<-plot_dat %>% 
  group_by(.imp, year, race_ethn, age, rptsrc) %>% 
  summarise(n_total = sum(n_total),
            pop = sum(pop)) %>% 
  mutate(total_pc = n_total/pop) %>% 
  ungroup()


ggplot(rpts_pc,
       aes(x = age, y = total_pc * 1000,
           color = race_ethn,
           fill = race_ethn)) + 
  geom_line() +
  #geom_ribbon(alpha = 0.5) +
  facet_wrap(~rptsrc) + 
  labs(title = "Child subjects of CPS investigations",
       subtitle = "US, 2018 by child race/ethnicity",
       y = "Rate per 1,000",
       x = "Age",
       color = "Race/Ethnicity")

### now just cats of mandated reporters
ggplot(rpts_pc %>% 
         filter(rptsrc%in%
                  c("education", "medical", "police",
                    "social services")),
       aes(x = age, y = total_pc * 1000,
           color = race_ethn,
           fill = race_ethn)) + 
  geom_line() +
  #geom_ribbon(alpha = 0.5) +
  facet_wrap(~rptsrc) + 
  labs(#title = "Age-specific rates of CPS investigation",
       #subtitle = "US, 2018 by child race/ethnicity and reporter type",
       y = "Rate per 1,000 children",
       x = "Age",
       color = "Race/Ethnicity")


```

## Report source by type of alleged maltreatment

```{r}
plot_dat<-nat_ncands %>% 
  mutate(chmal1 = case_when(
    chmal1 == 1 ~ "Physical abuse",
    chmal1 == 2 ~ "Neglect",
    chmal1 == 3 ~ "Medical neglect",
    chmal1 == 4 ~ "Sexual abuse",
    chmal1 == 5 ~ "Psychological / emotional",
    chmal1 == 6 ~ "No alleged maltreatment",
    chmal1 == 8 ~ "other",
    chmal1 == 9 ~ "unknown",
    is.na(chmal1) ~ "unknown"
  ))

mal_type<-plot_dat %>% 
  filter(!is.na(chmal1)) %>% 
  group_by(.imp, year, age, rptsrc, chmal1) %>% 
  summarise(n_total = sum(n_total)) %>% 
  ungroup()

ggplot(mal_type,
       aes(x = age, y = n_total,
           color = chmal1)) +
  geom_line() + 
  facet_wrap(~rptsrc) + 
  labs(x = "Age", y = "Children",
       color = "Alleged \nmaltreatment type",
       title = "Child subjects of CPS investigations",
       subtitle = "US, 2018 by type of alleged maltreatment")
```



## To do 

- substantiation rates by class of reporter / alleged type (natl)
- same but by state
- FC placement rates by class of reporter
- maps of rate ratio of referral rates by reporter type by state (Black/white, AIAN/white)
- more
